### PR TITLE
Chapter 20

### PR DESCRIPTION
**Pull request by yjunechoe**

### CODE REVIEW

**Review by jonthegeek — CHANGES_REQUESTED** [review]
I had to turn off evaluation in these blocks to get the book to build:
- 20-40
- 20-44
- 20-53
- 20-55

If that makes sense, I'll approve this, I just wanted you to take a look.

**Review by jonthegeek — CHANGES_REQUESTED** [review]
20-17 fails, too. That was working locally, I'm not sure what I changed.

**Review by jonthegeek — DISMISSED** [review]
Doh, had to kill another block. Weird that this built locally. I re-re-rebuilt to make sure.

**Review by jonthegeek — APPROVED** [review]
Ok, NOW it works.

I think you have an issue in ggtrace with R 4.2+. It's just producing a warning, but I *think* that's related to the failures. Otherwise it might be something in map?

**Comment by yjunechoe** [comment]
Thanks for the pointer! I can reproduce this.

I tracked down the warning and this is so embarassing. The one time I write a nested functional I do this - https://github.com/yjunechoe/ggtrace/commit/7fc1ff9fb6b9e49aeb3233ca95d74fed2fad021e

**Comment by jonthegeek** [comment]
@yjunechoe Woot for catching it!

**Pull request merged**
